global function CodeCallback_MapInit
global function initFrontierDefenseData

void function CodeCallback_MapInit()
{
	// Load Frontier Defense Data
	if( GameRules_GetGameMode() == "fd" )
		initFrontierDefenseData()
}


void function initFrontierDefenseData()
{

    shopPosition = 	< 5468.37, -5255.93, 76.1794 >
	shopAngles =   < 0, 167.288, 0 >
	FD_spawnPosition = < 5602.67, -4332.24, 63.5776 >
	FD_spawnAngles = < 0, -175.996, 0 >
	FD_groundspawnPosition = < 5602.67, -4332.24, 63.5776 >
	FD_groundspawnAngles = < 0, -175.996, 0 >

	FD_DropPodSpawns.append(<  5437.55, -4980.94, 93.4189  >)
	FD_DropPodSpawns.append(< 1945.36, -5167.86, 344.031 >)
	FD_DropPodSpawns.append( < 5814.85, -4205.24, 59.7183 > )

	AddStationaryAIPosition(< -5372.98, -1453.93, 225.78 >, eStationaryAIPositionTypes.SNIPER_TITAN)
	AddStationaryAIPosition(< -3992.91, -1028.97, 433.72 >, eStationaryAIPositionTypes.SNIPER_TITAN)
	AddStationaryAIPosition(< -3424.84, -4606.23, 475.59 >, eStationaryAIPositionTypes.SNIPER_TITAN)


	FD_HarvesterBatteryPort = < 4590.27, -4506.55, 208.031 >
	FD_HarvesterBatteryPortAngles = < 0, -121.849, 0 >

	array<vector> zuo = []
	zuo.append(  < 2293.88, -6121.12, 137.353 > )
    zuo.append(  < 1935.92, -5798.34, 136.652> )

	array<vector> you = []
	you.append(  < 1448.52, -2370.97, 91.5528 >)
    you.append(  < 1985.73, -2221.96, 99.0813 > )
	array<vector> mid = []
	mid.append( < -1498.16, -4493.82, 187.327 >)
    mid.append(   < -1346.99, -3380.25, -2.07985 > )

	array<vector> hou = []
    hou.append( < -1581.64, -2000.07, -95.3992 >)
    hou.append( < -2031.07, -1908.48, 62.4058 > )
    hou.append( < -2408.78, -2042.68, 271.598 > )
    hou.append( < -2613.49, -2351.93, 433.828 > )
    hou.append( < -2264.29, -2584.48, 460.077 > )
    hou.append( < -2778.06, -2917.05, 499.503 > )
    hou.append( < -2838.69, -3342.83, 497.004 > )
    hou.append( < -2910.02, -4228.78, 464.108 > )
    hou.append( < -3521.46, -4364.47, 489.746 > )
    hou.append( < -4361.49, -3908.89, 405.382 > )
    hou.append( < -4145.72, -3026.42, 473.525 > )
    hou.append( < -4140.97, -1601.95, 354.597 > )
    hou.append( < -3915.56, -1092.28, 445.84 > )

	array<vector> pao = []
    pao.append(< -4050.69, -1627.95, 358.488 >)
    pao.append(< -5341.97, -1640.48, 229.263 >)
    pao.append(< -5474.07, -2541.25, 283.281 >)
    pao.append(< -5231.72, -3243.84, 317.659 >)
    pao.append(< -4435.82, -3873.04, 391.567 >)
    pao.append(< -4126.64, -3328.3, 465.033 > )
    pao.append(< -3590.25, -4387.19, 489.318 >)

	array<vector> infantryspawns = []
    infantryspawns.append( < 1863.2, -2182.65, 85.8507 > )
    infantryspawns.append( < 1427.17, -2253.17, 48.5487 >)
    infantryspawns.append( < 1465.78, -2557.65, 132.114 >)
    infantryspawns.append( < 1429.38, -3394.62, 148.535 >)
    infantryspawns.append( < 1317.45, -4201.78, 145.86 > )
    infantryspawns.append( < 1215.48, -4751.61, 130.752 >)
    infantryspawns.append( < 1170.05, -5033.46, 134.562 > )
    infantryspawns.append( < 1582.97, -6144.66, 160.547 >)
    infantryspawns.append( < 2038.25, -6029.14, 133.227 >)
    infantryspawns.append(< -1475.96, -4575.68, 185.189 > )
    infantryspawns.append(< -1400.78, -4025.67, 126.021 > )
    infantryspawns.append(< -1396.15, -3412.93, 6.96361 > )
    infantryspawns.append(< -1271.99, -2056.29, -193.947 >)
    infantryspawns.append(< -2635.26, -2194.49, 397.043 > )
    infantryspawns.append(< -1999.08, -2620.54, 457.899 > )
    infantryspawns.append(< -2785.55, -2861.22, 495.755 > )
    infantryspawns.append(< -2882.33, -4314.73, 452.339 > )
    infantryspawns.append(< -3791.95, -4323.24, 479.574 > )


	int spawnamount

	int index = 1
    array<WaveEvent> wave1
	// for( spawnamount = 0; spawnamount < 20; spawnamount++ )
	//  {
	// wave1.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	// wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	// wave1.append(CreateWaitUntilAliveEvent( 40, index++ ) )
	//  }
	wave1.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave1.append(CreateMonarchTitanEvent(< 1633.54 ,-2238.62 , 80.04 >,< 0 , -10 , 0 >,"",index++))//右一
	wave1.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	wave1.append(CreateWaitUntilAliveEvent( 1, index++ ) )
	wave1.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	wave1.append(CreateWaitForTimeEvent( 20.0, index++ ) )
	wave1.append( CreateSmokeEvent( < 3625 , -4583, 24.1857>, 220, index++ ) )
	wave1.append( CreateSmokeEvent( < 3625 , -4583, 224.1857>, 220, index++ ) )
	for( spawnamount = 0; spawnamount < 16; spawnamount++ )
	{
		wave1.append(CreateDroppodGruntEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
		wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 5 ),index++))
		wave1.append(CreateWaitUntilAliveEvent( 40, index++ ) )
	}
	wave1.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	wave1.append(CreateMonarchTitanEvent(< 1771.87 , -6136.99 ,146.18 >,< 0 , -10 , 0 >,"",index++))
	wave1.append(CreateSpawnDroneEvent(< -240 ,-3056 ,2224>,< 0.004999 , -115.792000 , 0.000004 >,"drone0",index++, true ))
	wave1.append(CreateWaitUntilAliveEvent( 0, index++ ) )
	wave1.append( CreateSmokeEvent( < 3625 , -4583, 24.1857>, 220, index++ ) )
	wave1.append( CreateSmokeEvent( < 3625 , -4583, 224.1857>, 220, index++ ) )
	for( spawnamount = 0; spawnamount < 16; spawnamount++ )
	{
		wave1.append(CreateDroppodGruntEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
		wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 5 ),index++))
		wave1.append(CreateDroppodGruntEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
		wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 5 ),index++))
		wave1.append(CreateDroppodStalkerEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
		wave1.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 0.6 ),index++))
		wave1.append(CreateWaitUntilAliveEvent( 40, index++ ) )
	}
	//wave1.append( CreateSmokeEvent( < -12, 1720, 1540 >, 90, index++ ) )
	// wave1.append(CreateWaitForTimeEvent(0.3,index++))
	wave1.append(CreateWaitForTimeEvent( 5.0, index++ ) )

	wave1.append( CreateSmokeEvent( < 3625 , -4583, 24.1857>, 120, index++ ) )
	wave1.append( CreateSmokeEvent( < 3625 , -4583, 224.1857>, 120, index++ ) )
	wave1.append(CreateMonarchTitanEvent(< -4499.95 ,-1335.20 , 328.67 >,< 0 , -10 , 0 >,"",index++))
	wave1.append(CreateDroppodStalkerEvent(< -4482.62 , -3813.63 , 384.62 >,"",index++))//后左3
	wave1.append(CreateWaitForTimeEvent(0.8,index++))
	wave1.append(CreateDroppodGruntEvent(< -3628.56 , -4314.62 , 490.84>,"",index++))//后左2
	wave1.append(CreateWaitForTimeEvent(0.4,index++))
	wave1.append(CreateDroppodGruntEvent(< -2974.43 , -4352.02 ,459.73 >,"",index++))//后左1
	wave1.append(CreateWaitForTimeEvent(0.6,index++))
	wave1.append(CreateSuperSpectreEventWithMinion(< 1284.05 , -4376.64 , 153.14 >,< 0 , 0 , 0 >,"",index++))
	wave1.append(CreateWaitForTimeEvent(5.0,index++))
	wave1.append(CreateDroppodStalkerEvent(< -4499.95 ,-1335.20 , 328.67 >,"",index++))//迫击炮6
	wave1.append(CreateWaitForTimeEvent(0.2,index++))
	wave1.append(CreateDroppodGruntEvent(< -5450.80 ,-1392.08 , 202.86 >,"",index++))//迫击炮5
	wave1.append(CreateWaitForTimeEvent(5.0,index++))
	wave1.append(CreateSuperSpectreEvent(< -5338.37 ,-2537.82 , 269.87 >,< 0 , 0 , 0 >,"",index++))//迫击炮4
	wave1.append(CreateWaitForTimeEvent(0.1,index++))
	wave1.append(CreateDroppodStalkerEvent(< -5432.52 , -3099.92 , 322.12 >,"",index++))//迫击炮3
	wave1.append(CreateWaitForTimeEvent(0.2,index++))
	wave1.append(CreateDroppodGruntEvent(< -4434.57 , -3806.52 , 390.79 >,"",index++))//迫击炮2
	wave1.append(CreateWaitForTimeEvent(0.3,index++))
	wave1.append(CreateDroppodStalkerEvent(< -4111.51 , -3063.11 , 473.78 >,"",index++))//迫击炮1
	wave1.append(CreateWaitForTimeEvent(0.4,index++))
	wave1.append(CreateDroppodGruntEvent(< -3260.79 , -2982.36 , 498.32>,"",index++))//后右4
	wave1.append(CreateWaitForTimeEvent(0.5,index++))
	wave1.append(CreateDroppodStalkerEvent(< -2730.35 , -3059.87 , 488.75 >,"",index++))//后右3
	wave1.append(CreateWaitForTimeEvent(5.0,index++))
	wave1.append(CreateSuperSpectreEvent(< -2640.37 , -2653.26 , 457.57 >,< 0 , 0 , 0 >,"",index++))//后右2
	wave1.append(CreateWaitForTimeEvent(0.8,index++))
	wave1.append(CreateDroppodStalkerEvent(< -1624.42 , -2144.02, -78.93 >,"",index++))//后右1
	wave1.append(CreateWaitForTimeEvent(0.4,index++))
	wave1.append(CreateDroppodStalkerEvent(< 2611.32 , -2095.84 , 60.79 >,"",index++))//前右2
	wave1.append(CreateWaitForTimeEvent(0.2,index++))
	wave1.append(CreateDroppodStalkerEvent(< 1633.54 ,-2238.62 , 80.04 >,"",index++))//前右1
	wave1.append(CreateWaitForTimeEvent(0.7,index++))
	wave1.append(CreateDroppodGruntEvent(< 1491.55 , -3297.66 , 136.47 >,"",index++))//前中2
	wave1.append(CreateWaitForTimeEvent(0.1,index++))
	wave1.append(CreateDroppodStalkerEvent(< 1284.05 , -4376.64 , 153.14 >,"",index++))//前中1
	wave1.append(CreateWaitForTimeEvent(5.0,index++))
	wave1.append(CreateWaitUntilAliveEvent( 6, index++ ) )
	//wave1.append(CreateIonTitanEvent(< 2915.77, -6152.73, 110.00 >,< 0 , -35 , 0 >,"",index++))//左二
	wave1.append(CreateWaitForTimeEvent( 5.0, index++ ) )
	wave1.append(CreateWarningEvent( FD_IncomingWarnings.MortarTitan, index++ ) )
	wave1.append(CreateMortarTitanEvent(<  -4244.25  , -1751.26  , 343.567 >,< 0 , -10 , 0 >,0))
	waveEvents.append(wave1)


	index = 1
	array<WaveEvent> wave2

	// wave2.append(CreateRandomMortarTitanEvent(ora,< -0, 0, 0>,"",index++))
	// wave2.append(CreateWaitForTimeEvent( 3.0, index++ ) )
	// wave2.append(CreateRandomArcTitanEvent(ora,< -0, 0, 0>,"",index++))
	// wave2.append(CreateWaitForTimeEvent( 3.0, index++ ) )
	// wave2.append(CreateRandomArcTitanEvent(ora,< -0, 0, 0>,"",index++))
	// wave2.append(CreateWaitForTimeEvent( 3.0, index++ ) )
	wave2.append(CreateWarningEvent( FD_IncomingWarnings.Reaper, index++ ))
	 for( spawnamount = 0; spawnamount < 10; spawnamount++ )
	 {
	 	wave2.append(CreateDroppodGruntEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
	 	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	 	wave2.append(CreateDroppodGruntEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
	 	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	 	wave2.append(CreateDroppodStalkerEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
	 	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
		wave2.append(CreateDroppodGruntEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
	 	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3),index++))
	 	wave2.append(CreateDroppodGruntEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
	 	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
		wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 	wave2.append(CreateWaitUntilAliveEvent( 50, index++ ) )
	 }
	wave2.append(CreateWarningEvent( FD_IncomingWarnings.EnemyTitansIncoming, index++ ))
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(CreateWaitUntilAliveEvent( 20, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append( CreateRandomToneSniperTitanEvent( you , < 0.000000, 169.541000, 0.000000 >, index++ ) )
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt(6) ](zuo,< -0, 0, 0>,"",index++))
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 6 ) ](hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 6 ) ](hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 6 ) ](hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 6 ) ](hou,< -0, 0, 0>,"",index++))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++,1,"",-1))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++,1,"",-1))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	wave2.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	wave2.append(CreateWaitForTimeEvent( 20.0, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++,1,"",-1))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++,1,"",-1))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave2.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	wave2.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	wave2.append(CreateWaitForTimeEvent( 20.0, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++,1,"",-1))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	wave2.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave2.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave2.append(RandomtitanTypes[ RandomInt( 5 ) ](hou,< -0, 0, 0>,"",index++,1,"",-1))
	wave2.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave2.append(CreateSuperSpectreEvent(< 2293.88, -6121.12, 137.353  >,< 0 , 145 , 0 >,"",0))
	waveEvents.append(wave2)
	 index = 1
    array<WaveEvent> wave3
	wave3.append(CreateWarningEvent( FD_IncomingWarnings.ArcTitanIntro, index++ ))
	wave3.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave3.append(CreateRandomToneSniperTitanEvent(you,< -0, 0, 0>,index++,1,"",0))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomToneSniperTitanEvent(zuo,< -0, 0, 0>,index++,1,"",0))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	wave3.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave3.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave3.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave3.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave3.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomToneSniperTitanEvent(zuo,< -0, 0, 0>,index++,1,"",0))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateRandomNukeTitanEvent(zuo,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave3.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave3.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave3.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave3.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave3.append( CreateWaitForTimeEvent( 1.3, index++ ) )
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	wave3.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",0))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave3.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave3.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	wave3.append(CreateSuperSpectreEvent(< 2293.88, -6121.12, 137.353  >,< 0 , 145 , 0 >,"",0))
	waveEvents.append(wave3)



	 index = 1
    array<WaveEvent> wave4

	wave4.append(CreateWarningEvent( FD_IncomingWarnings.HeavyWave, index++ ))
	 for( spawnamount = 0; spawnamount < 5; spawnamount++ )
	 {
	 wave4.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	 wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2),index++))
	 wave4.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	 wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2),index++))
	 wave4.append(CreateSpawnDroneEvent(< -240 ,-3056 ,2224>,< 0.004999 , -115.792000 , 0.000004 >,"drone0",index++, true ))
	 wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave4.append(CreateDroppodStalkerEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
	 wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	 wave4.append(CreateDroppodStalkerEvent( infantryspawns[ RandomInt( infantryspawns.len() ) ] ,"",index++))
	 wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave4.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	 wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave4.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	 wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave4.append(CreateSpawnDroneEvent(< -240 ,-3056 ,2224>,< 0.004999 , -115.792000 , 0.000004 >,"drone0",index++, true ))
	 wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 5, 8 ),index++))
	 wave4.append(CreateWaitUntilAliveEvent( 40, index++ ) )
	 wave4.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 }
	wave4.append(CreateWarningEvent( FD_IncomingWarnings.PreNukeTitan, index++ ))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )

	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 14, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )

	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))

	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append( CreateWaitForAllTitansDeadEvent( 8, index++ ) )
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomArcTitanEvent(hou,< -0, 0, 0>,"",index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))

	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )


	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append( CreateWaitForAllTitansDeadEvent( 1, index++ ) )
	wave4.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	wave4.append(CreateWaitForTimeEvent( RandomFloatRange( 0.1, 3 ),index++))
	wave4.append(CreateLegionTitanEvent(< 2293.88, -6121.12, 137.353  >,< 0 , -30 , 0 >,"",0))
	waveEvents.append(wave4)
	index = 1

	 array<WaveEvent> wave5

	 wave5.append(CreateRandomToneSniperTitanEvent(you,< -0, 0, 0>,index++,1,"",0))
	 wave5.append(CreateWaitUntilAliveEvent( 4, index++ ) )
	 wave5.append(CreateWarningEvent( FD_IncomingWarnings.Everything, index++ ))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomToneSniperTitanEvent(zuo,< -0, 0, 0>,index++,1,"",0))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 8, index++ ) )
	 wave5.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 8, index++ ) )
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomToneSniperTitanEvent(you,< -0, 0, 0>,index++,1,"",0))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 8, index++ ) )
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomToneSniperTitanEvent(you,< -0, 0, 0>,index++,1,"",0))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 8, index++ ) )
	 wave5.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(zuo,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 8, index++ ) )
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 8, index++ ) )
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 8, index++ ) )
	 wave5.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomToneSniperTitanEvent(you,< -0, 0, 0>,index++,1,"",1))
	 wave5.append(CreateRandomNukeTitanEvent(zuo,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	 wave5.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateSpawnDroneEvent(< -240 ,-3056 ,2224>,< 0.004999 , -115.792000 , 0.000004 >,"drone0",index++, true ))
	 wave5.append(CreateRandomToneSniperTitanEvent(zuo,< -0, 0, 0>,index++,1,"",1))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(you,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	 wave5.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(you,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	 wave5.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	 wave5.append(CreateRandomMortarTitanEvent(pao,< -0, 0, 0>,index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 6, index++ ) )
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomToneSniperTitanEvent(you,< -0, 0, 0>,index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	 wave5.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateSpawnDroneEvent(< -240 ,-3056 ,2224>,< 0.004999 , -115.792000 , 0.000004 >,"drone0",index++, true ))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 12, index++ ) )
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomToneSniperTitanEvent(you,< -0, 0, 0>,index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 18, index++ ) )
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	 wave5.append(CreateSpawnDroneEvent(< -352 ,-5792, 1664 >,< 0.004999 , -115.792000 , 0.000004 >,"drone1",index++, true ))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateSpawnDroneEvent(< -240 ,-3056 ,2224>,< 0.004999 , -115.792000 , 0.000004 >,"drone0",index++, true ))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomToneSniperTitanEvent(zuo,< -0, 0, 0>,index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateRandomToneSniperTitanEvent(zuo,< -0, 0, 0>,index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(RandomtitanTypes[ RandomInt(6) ](hou,< -0, 0, 0>,"",index++,1,"",FD_TitanType.TITAN_ELITE))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomToneSniperTitanEvent(you,< -0, 0, 0>,index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateSpawnDroneEvent(< -464 ,-4464, 1872 >,< 0.004999 , -115.792000 , 0.000004 >,"drone2",index++, true ))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append( CreateWaitForAllTitansDeadEvent( 16, index++ ) )
	 wave5.append( CreateRandomSuperSpectreEvent(infantryspawns,< -0, 0, 0>,"",index++))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateRandomNukeTitanEvent(hou,< -0, 0, 0>,"",index++,1,"",1))
	 wave5.append(CreateWaitForTimeEvent( RandomFloatRange( 1, 2 ),index++))
	 wave5.append(CreateLegionTitanEvent(< 2293.88, -6121.12, 137.353  >,< 0 , -30 , 0 >,"",0))
	 waveEvents.append(wave5)
}

